apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.backend.service.port | default 8080 }}
      targetPort: {{ .Values.backend.service.port | default 8080 }}
  selector:
    app: backend
