apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.frontend.service.port | default 80 }}
      targetPort: {{ .Values.frontend.service.port | default 80 }}
  selector:
    app: frontend-app

